const express = require("express");
const router = express.Router();
const userController = require("../controllers/userController");
const validateUser = require("../middleware/validateUser");
const validateRequest = require("../middleware/validateRequest");
router.post("/signup", validateUser, validateRequest, userController.register);
router.post("/login", validateUser, validateRequest, userController.login);
router.post("/fp", userController.forgetpass);
router.post("/verify", userController.verifyOtp);
module.exports = router;
